### ISSUE TITLE
Model is not working for different data-set

### ISSUE THREAD

**Issue by sanahtech** [AvivSham/SRGAN-Keras-Implementation#2] opened 2019-09-20 01:10 UTC
SRGAN model is working fine for given DIV2K_train_hr dataset. But I tried to train the same model for a different dataset. It does not work.

following is the error.
File "init.py", line 83, in
train(FLAGS)
File "/home/student/usama_lahore/Memona/perceptual-reflection-removal-master/SRGANmodelnewdata/SRGAN-Keras-Implementation-master/train.py", line 21, in train
srgan_model.train(epochs, save_interval = save_interval, batch_size = batch_size)
File "/home/student/usama_lahore/Memona/perceptual-reflection-removal-master/SRGANmodelnewdata/SRGAN-Keras-Implementation-master/models/SRGAN.py", line 225, in train
real_dis_loss = self.discriminator.train_on_batch(hr_imgs, real)
File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1211, in train_on_batch
class_weight=class_weight)
File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 751, in _standardize_user_data
exception_prefix='input')
File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_3 to have 4 dimensions, but got array with shape (16, 1)

**Comment by AvivSham** [comment] 2019-09-20 19:41
What is the shape of your input data?
Can you please mention which dataset are you using?

**Comment by sanahtech** [comment] 2019-09-21 14:21
for high resolution imgaes shape is (256,256,3) and for low resolution images its (64,64,3)
I have used 1386 images of COCO 2017 train data-set..

**Comment by AvivSham** [comment] 2019-09-25 18:32
I saw you opened a similar issue in other repo. did you try to debug your code? did you added further preprocessing process?  
Please give more info.
Can you please drop here an screen shot when you print the shape of the batch you try to generate? 
And when building the SRGAN module did you pass the path of the images? (it might be related to how the dataset is structured on your PC)

**Comment by sanahtech** [comment] 2019-09-25 18:42
yes, I have debug the code. Problem occurs in model/SRGAN.py file in def gen_pipeline function. self.high_reso_imgs[indx_high] has 2 dimensional shape while it should be 4 dimensional. but I'm not able to understand the reason.
I did not add any pre-processing step.

**Comment by AvivSham** [comment] 2019-09-25 18:56
you need to create one folder with all of the HR images and when you built the SRGAN module you need to pass the path to this folder. 
Have you structured your data in this manner?

**Comment by sanahtech** [comment] 2019-09-25 18:59
Yes. I did. SRGAN model reading images from given data-set.

**Comment by AvivSham** [comment] 2019-09-25 19:05
please write here how did you call it from the command line.
It's a bit hard for me to help you like this because if you indeed debugged the code how come you don't know why the shapes of the images come out like that from the generator?

**Comment by sanahtech** [comment] 2019-09-25 19:12
!python3 init.py --mode train --dir-path newdata

I have changed the file type in utils.py def prepare_data function from .png to .jpg. because images have .jpg file extension.
I have also tried to train this model on some other images(collected from google) but it did not work for that data-set as well.

**Comment by AvivSham** [comment] 2019-09-25 19:14
what `newdata` holds?

**Comment by sanahtech** [comment] 2019-09-25 19:17
its a folder name having 1386 images of COCO 2017 train data-set. which is placed in the same directory.

**Comment by sanahtech** [comment] 2019-09-25 19:18
I also provided model a data-set of randomly collected images from google. same error occurred

**Comment by AvivSham** [comment] 2019-09-25 19:22
folder name or full path? try to pass full path
if it doesn't help please break it into smaller problem take the generator function and try to see what happens I would have isolated it from the code. if the generator works there is no reason why the training shouldn't work.

**Comment by sanahtech** [comment] 2019-09-25 19:24
utils.py works perfectly fine. it reads images. 
Alright. I'll try again

**Comment by AvivSham** [comment] 2019-09-25 19:29
Try to go line by line before the generator. As I said there is no doubt the problem is with the generator, once it solved the code should run without problems

**Comment by AvivSham** [comment] 2019-09-27 09:39
is the problem solved? if so please share here what was the problem and I will close this issue

**Comment by sanahtech** [comment] 2019-10-01 16:46
yes. problem was because of data-set. some images have dimensions less than 256X256. while high resolution images must have 256X256 dimensions. So, I resized the images to 256X256 dimensions after center cropped.

**Comment by AvivSham** [comment] 2019-10-02 05:48
Great happy that it works now :)

**Closed as completed by AvivSham** 2019-10-02 05:48 UTC
